project:
  type: website

website:
  title: "Alex Cano | Portfolio"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Sobre mí"
        href: about.qmd
      - text: "Proyectos"
        menu:
          - text: "Todos los proyectos"
            href: projects/index.qmd
          - text: "WordPress Dev en Local"
            href: projects/wordpress-dev-en-local.qmd
          - text: "WordPress CD/CI con Jenkins"
            href: projects/wordpress-jenkins.qmd
      - text: "Certificaciones"
        href: certifications.qmd
      - text: "Contacto"
        href: contact.qmd
